# -*- coding: utf-8 -*-
"""proj1-hello_world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qkPp4KuSBCXbs6gfIo8U1qQMtry50KCe

This notebook highlights my use of introductary commands such as print, defining variables, importing libraries, and loading datasets. Based on Chapter 1 of OpenStax textbook 'Principles of Data Science' by Ault, Liao, Musolino, Bukaita, and Zentner.
"""

print ("hello world!")

# defining a variable and printing its value
a = 1
print ("the a value in the first cell:", a)

# defining a variable and performing math on it
b = 3
print ("a in the second cell:", a)
print ("b in the second cell:", b)
a + b

# changing a variable value may change it in previous code blocks where the variable is not re-defined
a = 2
a + b
# this is why "Run all" or "Run before" is useful

# importing a library under a callname
import pandas as pd

# reading in a dataset
iris = pd.read_csv("iris.csv")
iris

# using .describe() to summarize data
iris.describe()

# selecting a data column from a dataset using the attribute name
iris['petal.length']

# selecting a data column from a dataset using indicies
iris.iloc[:, 3]

# selecting a specific entry attribute using indicies
print (iris['petal.length'][0])
print (iris['petal.length'][107])

# selecting a small subset of entries and attributes using indicies
iris.iloc[[1,53,106], [1,2]]

# selecting a subset of data entries with a specific criteria
iris.loc[iris['petal.width'] >= 2.0]

# using MatPlotLib
import matplotlib.pyplot as plot
plot.scatter(iris['petal.length'], iris['petal.width'])
plot.title("Petal Length vs. Width")
plot.xlabel("Length")
plot.ylabel("Width")

# using MatPlotLib on a subset of the data
iris = pd.read_csv("iris.csv")
setosa = iris.loc[iris['variety'] == 'Setosa']
plot.scatter(setosa['petal.length'], setosa['petal.width'])
plot.title('Setosa Petal Length vs. Width')
plot.xlabel('Length')
plot.ylabel('Width')